name: CI Pipeline
on:
  workflow_dispatch:
  push:
     branches:
       - dev 
       - main
      
env:
        DOCKER_IMAGE: satinderkaura348/petapp:${{ github.sha }}
        MAVEN_OPTS: "-DskipTests=true"      

jobs:
  build:
    uses: ./.github/workflows/javabuild.yml
    secrets: inherit
  
  snyk:
     uses: ./.github/workflows/snyk.yml
     needs: build
     secrets: inherit     

  test:
    uses: ./.github/workflows/test.yml
    needs: snyk
    secrets: inherit  

  imagepush:
    uses: ./.github/workflows/imagepush.yml
    needs: test
    secrets: inherit  

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: imagepush
    secrets: inherit

