# .github/workflows/imagepush.yml
name: Docker Image Build and Push

on:
  workflow_call:

jobs:
  image_push:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: satinderkaura348/petapp:${{ github.sha }}
      DOCKER_IMAGE_LATEST: satinderkaura348/petapp:latest

    steps:
      
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Dockerfile copies target/*.jar
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: jar
          path: ./target
      
      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} -t ${{ env.DOCKER_IMAGE_LATEST }} .
          docker save ${{ env.DOCKER_IMAGE }} > docker_image.tar

      # Step 4: Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 5: Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ env.DOCKER_IMAGE }}
          docker push ${{ env.DOCKER_IMAGE_LATEST }}
