# .github/workflows/imagepush.yml
name: Docker Image Build and Push

on:
  workflow_call:

jobs:
  image_push:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: satinderkaura348/petapp:${{ github.sha }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Step 2: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }} .
          docker save ${{ env.DOCKER_IMAGE }} > docker_image.tar

      # Step 3: Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 4: Push Docker Image
      - name: Push Docker Image
        run: docker push ${{ env.DOCKER_IMAGE }}
