name: Docker Image Build and Push

on:
  workflow_call:

jobs:
  image_push:
    runs-on: ubuntu-latest
    needs: test
    env:
      DOCKER_IMAGE: satinderkaura348/petapp:${{ github.sha }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: sudo docker build -t ${{ env.DOCKER_IMAGE }} .

      - name: Snyk Docker Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk container test ${{ env.DOCKER_IMAGE }}

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: sudo docker push ${{ env.DOCKER_IMAGE }}
