name: Snyk Gradle Scan

on:
  workflow_call:

jobs:
  snyk-deps:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up NodeJS for Snyk
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk Gradle Dependency Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects
