name: Sonar Scan

on:
  workflow_call:

jobs:
  sonar:
    runs-on: ubuntu-latest
    needs: snyk-deps
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Run Sonar Scan
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=satinderkaura348-ops_devSecops_Pipeline \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
